(Line: 3, Col: 4): Unexpected value '', (Line: 4, Col: 1): Unexpected value 'workflow_dispatch', (Line: 22, Col: 1): Unexpected value 'test', (Line: 28, Col: 1): Unexpected value 'deploy'

on:
workflow_dispatch:

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone form github"


  build:
     runs-on: ubuntu-latest
     steps:
      - name: build docker container
        run: echo "build docker container"


test:
    runs-on: ubuntu-latest
    steps:
      - name: test code
        run: echo "testing code"

deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy code
        run: echo "deploying code"
