---
name: CI CD
on: null
workflow_dispatch: null

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone form github"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build docker container
        run: echo "build docker container"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test code
        run: echo "testing code"
  deploy:
    runs-on: ubuntu-latest
  steps:
    - name: deploy code
      run: echo "deploying code"
