name: CI CD

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone from github"

  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: build docker container
        run: echo "build docker container"

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: test code
        run: echo "testing code"

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy code
        run: echo "deploying code"
